In [7]:
import numpy as np
import pandas as pd
import cv2
import mediapipe as mp
from functions import draw_landmarks

In [17]:
testImg = cv2.imread("./Dataset/user_7/K8.jpg")
print(testImg)

[[[ 66  80  78]
  [ 66  80  78]
  [ 67  81  79]
  ...
  [117 134 130]
  [117 135 128]
  [117 135 128]]

 [[ 66  80  78]
  [ 66  80  78]
  [ 67  81  79]
  ...
  [116 133 129]
  [116 134 127]
  [117 135 128]]

 [[ 66  80  78]
  [ 67  81  79]
  [ 67  81  79]
  ...
  [118 135 131]
  [119 137 130]
  [121 139 132]]

 ...

 [[168 168 156]
  [166 166 154]
  [169 169 157]
  ...
  [ 14  11   6]
  [ 15  12   7]
  [ 16  13   8]]

 [[168 168 156]
  [165 165 153]
  [169 169 157]
  ...
  [ 14  11   6]
  [ 15  12   7]
  [ 17  14   9]]

 [[168 168 156]
  [165 165 153]
  [168 168 156]
  ...
  [ 14  11   6]
  [ 16  13   8]
  [ 17  14   9]]]


In [26]:
mp_hands = mp.solutions.hands
hands = mp_hands.Hands(min_detection_confidence=0.7, min_tracking_confidence=0.5)

In [49]:
dset = []

for i in range(1):
    addr = "./Dataset/user_3/A"
    imgaddr = addr + str(i) + ".jpg"
    img = cv2.imread(imgaddr)

    rgb_frame = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    results = hands.process(rgb_frame)

    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            for landmark in hand_landmarks.landmark:
                dset.append([landmark.x, landmark.y, landmark.z])

In [51]:
dset

[[[0.5055405497550964], [0.38857346773147583], [-5.237602067609259e-07]],
 [[0.5702322125434875], [0.34208643436431885], [-0.012312382459640503]],
 [[0.6178761124610901], [0.26392462849617004], [-0.01608561910688877]],
 [[0.6387125253677368], [0.18837779760360718], [-0.022614100947976112]],
 [[0.6147016286849976], [0.1368897706270218], [-0.02677234075963497]],
 [[0.5789148211479187], [0.19390727579593658], [-0.0011902159312739968]],
 [[0.5847315788269043], [0.12400412559509277], [-0.03033692017197609]],
 [[0.5818970203399658], [0.18751710653305054], [-0.045570943504571915]],
 [[0.5763342976570129], [0.2301713526248932], [-0.0500573106110096]],
 [[0.5375294089317322], [0.19430477917194366], [-0.00558115029707551]],
 [[0.5413678288459778], [0.13939273357391357], [-0.03561058267951012]],
 [[0.5434193015098572], [0.22191199660301208], [-0.04177134111523628]],
 [[0.5392136573791504], [0.25870847702026367], [-0.03908497095108032]],
 [[0.4959731698036194], [0.20561644434928894], [-0.014079055